# Generated by Django 3.2.16 on 2022-10-30 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('edad', models.CharField(max_length=3, verbose_name='Edad')),
            ],
        ),
        migrations.CreateModel(
            name='Acompanante',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calendar_medic.persona')),
                ('parentesco', models.CharField(max_length=100, verbose_name='parentesco')),
            ],
            bases=('calendar_medic.persona',),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calendar_medic.persona')),
                ('genero', models.CharField(max_length=30, verbose_name='Genero')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
            ],
            bases=('calendar_medic.persona',),
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha definida')),
                ('hora', models.TimeField(verbose_name='Fecha definida')),
                ('lugar', models.CharField(max_length=100, verbose_name='Lugar')),
                ('costo', models.CharField(max_length=20, verbose_name='Costo')),
                ('estado', models.CharField(max_length=40, verbose_name='Estado')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('acompanante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_medic.acompanante')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_medic.paciente')),
            ],
        ),
    ]
